package edu.usc.viterbi.dsci.dsci558project.dao;

import edu.usc.viterbi.dsci.dsci558project.dao.sqlprovider.PlayerPerfStatPerGameSqlProvider;
import edu.usc.viterbi.dsci.dsci558project.domain.PlayerPerfStatPerGame;
import edu.usc.viterbi.dsci.dsci558project.domain.PlayerPerfStatPerGameExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface PlayerPerfStatPerGameDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @SelectProvider(type= PlayerPerfStatPerGameSqlProvider.class, method="countByExample")
    long countByExample(PlayerPerfStatPerGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @DeleteProvider(type=PlayerPerfStatPerGameSqlProvider.class, method="deleteByExample")
    int deleteByExample(PlayerPerfStatPerGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @Delete({
        "delete from PLAYER_PERFORMANCE_STAT_PER_GAME",
        "where record_id = #{recordId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @Insert({
        "insert into PLAYER_PERFORMANCE_STAT_PER_GAME (record_id, player_id, ",
        "season, age, team_abbrv_name, ",
        "league, position, ",
        "G, GS, MP, ",
        "FG, FGA, FGP, ",
        "3P, 3PA, 3PP, ",
        "2P, 2PA, 2PP, ",
        "eFGP, FT, FTA, ",
        "FTP, ORB, DRB, ",
        "TRB, AST, STL, ",
        "BLK, TOV, PF, ",
        "PTS)",
        "values (#{recordId,jdbcType=VARCHAR}, #{playerId,jdbcType=VARCHAR}, ",
        "#{season,jdbcType=VARCHAR}, #{age,jdbcType=TINYINT}, #{teamAbbrvName,jdbcType=VARCHAR}, ",
        "#{league,jdbcType=VARCHAR}, #{position,jdbcType=VARCHAR}, ",
        "#{G,jdbcType=SMALLINT}, #{GS,jdbcType=SMALLINT}, #{MP,jdbcType=DOUBLE}, ",
        "#{FG,jdbcType=DOUBLE}, #{FGA,jdbcType=DOUBLE}, #{FGP,jdbcType=DOUBLE}, ",
        "#{_3P,jdbcType=DOUBLE}, #{_3PA,jdbcType=DOUBLE}, #{_3PP,jdbcType=DOUBLE}, ",
        "#{_2P,jdbcType=DOUBLE}, #{_2PA,jdbcType=DOUBLE}, #{_2PP,jdbcType=DOUBLE}, ",
        "#{eFGP,jdbcType=DOUBLE}, #{FT,jdbcType=DOUBLE}, #{FTA,jdbcType=DOUBLE}, ",
        "#{FTP,jdbcType=DOUBLE}, #{ORB,jdbcType=DOUBLE}, #{DRB,jdbcType=DOUBLE}, ",
        "#{TRB,jdbcType=DOUBLE}, #{AST,jdbcType=DOUBLE}, #{STL,jdbcType=DOUBLE}, ",
        "#{BLK,jdbcType=DOUBLE}, #{TOV,jdbcType=DOUBLE}, #{PF,jdbcType=DOUBLE}, ",
        "#{PTS,jdbcType=DOUBLE})"
    })
    int insert(PlayerPerfStatPerGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @InsertProvider(type=PlayerPerfStatPerGameSqlProvider.class, method="insertSelective")
    int insertSelective(PlayerPerfStatPerGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @SelectProvider(type=PlayerPerfStatPerGameSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="record_id", property="recordId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="player_id", property="playerId", jdbcType=JdbcType.VARCHAR),
        @Result(column="season", property="season", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.TINYINT),
        @Result(column="team_abbrv_name", property="teamAbbrvName", jdbcType=JdbcType.VARCHAR),
        @Result(column="league", property="league", jdbcType=JdbcType.VARCHAR),
        @Result(column="position", property="position", jdbcType=JdbcType.VARCHAR),
        @Result(column="G", property="G", jdbcType=JdbcType.SMALLINT),
        @Result(column="GS", property="GS", jdbcType=JdbcType.SMALLINT),
        @Result(column="MP", property="MP", jdbcType=JdbcType.DOUBLE),
        @Result(column="FG", property="FG", jdbcType=JdbcType.DOUBLE),
        @Result(column="FGA", property="FGA", jdbcType=JdbcType.DOUBLE),
        @Result(column="FGP", property="FGP", jdbcType=JdbcType.DOUBLE),
        @Result(column="3P", property="_3P", jdbcType=JdbcType.DOUBLE),
        @Result(column="3PA", property="_3PA", jdbcType=JdbcType.DOUBLE),
        @Result(column="3PP", property="_3PP", jdbcType=JdbcType.DOUBLE),
        @Result(column="2P", property="_2P", jdbcType=JdbcType.DOUBLE),
        @Result(column="2PA", property="_2PA", jdbcType=JdbcType.DOUBLE),
        @Result(column="2PP", property="_2PP", jdbcType=JdbcType.DOUBLE),
        @Result(column="eFGP", property="eFGP", jdbcType=JdbcType.DOUBLE),
        @Result(column="FT", property="FT", jdbcType=JdbcType.DOUBLE),
        @Result(column="FTA", property="FTA", jdbcType=JdbcType.DOUBLE),
        @Result(column="FTP", property="FTP", jdbcType=JdbcType.DOUBLE),
        @Result(column="ORB", property="ORB", jdbcType=JdbcType.DOUBLE),
        @Result(column="DRB", property="DRB", jdbcType=JdbcType.DOUBLE),
        @Result(column="TRB", property="TRB", jdbcType=JdbcType.DOUBLE),
        @Result(column="AST", property="AST", jdbcType=JdbcType.DOUBLE),
        @Result(column="STL", property="STL", jdbcType=JdbcType.DOUBLE),
        @Result(column="BLK", property="BLK", jdbcType=JdbcType.DOUBLE),
        @Result(column="TOV", property="TOV", jdbcType=JdbcType.DOUBLE),
        @Result(column="PF", property="PF", jdbcType=JdbcType.DOUBLE),
        @Result(column="PTS", property="PTS", jdbcType=JdbcType.DOUBLE)
    })
    List<PlayerPerfStatPerGame> selectByExample(PlayerPerfStatPerGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @Select({
        "select",
        "record_id, player_id, season, age, team_abbrv_name, league, position, G, GS, ",
        "MP, FG, FGA, FGP, 3P, 3PA, 3PP, 2P, 2PA, 2PP, eFGP, FT, FTA, FTP, ORB, DRB, ",
        "TRB, AST, STL, BLK, TOV, PF, PTS",
        "from PLAYER_PERFORMANCE_STAT_PER_GAME",
        "where record_id = #{recordId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="record_id", property="recordId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="player_id", property="playerId", jdbcType=JdbcType.VARCHAR),
        @Result(column="season", property="season", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.TINYINT),
        @Result(column="team_abbrv_name", property="teamAbbrvName", jdbcType=JdbcType.VARCHAR),
        @Result(column="league", property="league", jdbcType=JdbcType.VARCHAR),
        @Result(column="position", property="position", jdbcType=JdbcType.VARCHAR),
        @Result(column="G", property="G", jdbcType=JdbcType.SMALLINT),
        @Result(column="GS", property="GS", jdbcType=JdbcType.SMALLINT),
        @Result(column="MP", property="MP", jdbcType=JdbcType.DOUBLE),
        @Result(column="FG", property="FG", jdbcType=JdbcType.DOUBLE),
        @Result(column="FGA", property="FGA", jdbcType=JdbcType.DOUBLE),
        @Result(column="FGP", property="FGP", jdbcType=JdbcType.DOUBLE),
        @Result(column="3P", property="_3P", jdbcType=JdbcType.DOUBLE),
        @Result(column="3PA", property="_3PA", jdbcType=JdbcType.DOUBLE),
        @Result(column="3PP", property="_3PP", jdbcType=JdbcType.DOUBLE),
        @Result(column="2P", property="_2P", jdbcType=JdbcType.DOUBLE),
        @Result(column="2PA", property="_2PA", jdbcType=JdbcType.DOUBLE),
        @Result(column="2PP", property="_2PP", jdbcType=JdbcType.DOUBLE),
        @Result(column="eFGP", property="eFGP", jdbcType=JdbcType.DOUBLE),
        @Result(column="FT", property="FT", jdbcType=JdbcType.DOUBLE),
        @Result(column="FTA", property="FTA", jdbcType=JdbcType.DOUBLE),
        @Result(column="FTP", property="FTP", jdbcType=JdbcType.DOUBLE),
        @Result(column="ORB", property="ORB", jdbcType=JdbcType.DOUBLE),
        @Result(column="DRB", property="DRB", jdbcType=JdbcType.DOUBLE),
        @Result(column="TRB", property="TRB", jdbcType=JdbcType.DOUBLE),
        @Result(column="AST", property="AST", jdbcType=JdbcType.DOUBLE),
        @Result(column="STL", property="STL", jdbcType=JdbcType.DOUBLE),
        @Result(column="BLK", property="BLK", jdbcType=JdbcType.DOUBLE),
        @Result(column="TOV", property="TOV", jdbcType=JdbcType.DOUBLE),
        @Result(column="PF", property="PF", jdbcType=JdbcType.DOUBLE),
        @Result(column="PTS", property="PTS", jdbcType=JdbcType.DOUBLE)
    })
    PlayerPerfStatPerGame selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @UpdateProvider(type=PlayerPerfStatPerGameSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") PlayerPerfStatPerGame record, @Param("example") PlayerPerfStatPerGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @UpdateProvider(type=PlayerPerfStatPerGameSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") PlayerPerfStatPerGame record, @Param("example") PlayerPerfStatPerGameExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @UpdateProvider(type=PlayerPerfStatPerGameSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(PlayerPerfStatPerGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_PERFORMANCE_STAT_PER_GAME
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @Update({
        "update PLAYER_PERFORMANCE_STAT_PER_GAME",
        "set player_id = #{playerId,jdbcType=VARCHAR},",
          "season = #{season,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=TINYINT},",
          "team_abbrv_name = #{teamAbbrvName,jdbcType=VARCHAR},",
          "league = #{league,jdbcType=VARCHAR},",
          "position = #{position,jdbcType=VARCHAR},",
          "G = #{G,jdbcType=SMALLINT},",
          "GS = #{GS,jdbcType=SMALLINT},",
          "MP = #{MP,jdbcType=DOUBLE},",
          "FG = #{FG,jdbcType=DOUBLE},",
          "FGA = #{FGA,jdbcType=DOUBLE},",
          "FGP = #{FGP,jdbcType=DOUBLE},",
          "3P = #{_3P,jdbcType=DOUBLE},",
          "3PA = #{_3PA,jdbcType=DOUBLE},",
          "3PP = #{_3PP,jdbcType=DOUBLE},",
          "2P = #{_2P,jdbcType=DOUBLE},",
          "2PA = #{_2PA,jdbcType=DOUBLE},",
          "2PP = #{_2PP,jdbcType=DOUBLE},",
          "eFGP = #{eFGP,jdbcType=DOUBLE},",
          "FT = #{FT,jdbcType=DOUBLE},",
          "FTA = #{FTA,jdbcType=DOUBLE},",
          "FTP = #{FTP,jdbcType=DOUBLE},",
          "ORB = #{ORB,jdbcType=DOUBLE},",
          "DRB = #{DRB,jdbcType=DOUBLE},",
          "TRB = #{TRB,jdbcType=DOUBLE},",
          "AST = #{AST,jdbcType=DOUBLE},",
          "STL = #{STL,jdbcType=DOUBLE},",
          "BLK = #{BLK,jdbcType=DOUBLE},",
          "TOV = #{TOV,jdbcType=DOUBLE},",
          "PF = #{PF,jdbcType=DOUBLE},",
          "PTS = #{PTS,jdbcType=DOUBLE}",
        "where record_id = #{recordId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(PlayerPerfStatPerGame record);

}
