package edu.usc.viterbi.dsci.dsci558project.domain;

import com.fasterxml.jackson.annotation.JsonProperty;

public class PlayerPerfStatPerGame {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.record_id
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.player_id
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private String playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.season
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private String season;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.age
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.team_abbrv_name
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private String teamAbbrvName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.league
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private String league;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.position
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.G
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Integer G;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.GS
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Integer GS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.MP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double MP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FG
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double FG;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FGA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double FGA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FGP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double FGP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.3P
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @JsonProperty("3p")
    private Double _3P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.3PA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @JsonProperty("3pa")
    private Double _3PA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.3PP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @JsonProperty("3pp")
    private Double _3PP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.2P
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @JsonProperty("2p")
    private Double _2P;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.2PA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @JsonProperty("2pa")
    private Double _2PA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.2PP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    @JsonProperty("2pp")
    private Double _2PP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.eFGP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double eFGP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FT
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double FT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FTA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double FTA;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FTP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double FTP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.ORB
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double ORB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.DRB
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double DRB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.TRB
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double TRB;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.AST
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double AST;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.STL
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double STL;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.BLK
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double BLK;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.TOV
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double TOV;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.PF
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double PF;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_PERFORMANCE_STAT_PER_GAME.PTS
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    private Double PTS;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.record_id
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.record_id
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.record_id
     *
     * @param recordId the value for PLAYER_PERFORMANCE_STAT_PER_GAME.record_id
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.player_id
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.player_id
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public String getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.player_id
     *
     * @param playerId the value for PLAYER_PERFORMANCE_STAT_PER_GAME.player_id
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setPlayerId(String playerId) {
        this.playerId = playerId == null ? null : playerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.season
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.season
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public String getSeason() {
        return season;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.season
     *
     * @param season the value for PLAYER_PERFORMANCE_STAT_PER_GAME.season
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setSeason(String season) {
        this.season = season == null ? null : season.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.age
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.age
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.age
     *
     * @param age the value for PLAYER_PERFORMANCE_STAT_PER_GAME.age
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.team_abbrv_name
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.team_abbrv_name
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public String getTeamAbbrvName() {
        return teamAbbrvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.team_abbrv_name
     *
     * @param teamAbbrvName the value for PLAYER_PERFORMANCE_STAT_PER_GAME.team_abbrv_name
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setTeamAbbrvName(String teamAbbrvName) {
        this.teamAbbrvName = teamAbbrvName == null ? null : teamAbbrvName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.league
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.league
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public String getLeague() {
        return league;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.league
     *
     * @param league the value for PLAYER_PERFORMANCE_STAT_PER_GAME.league
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setLeague(String league) {
        this.league = league == null ? null : league.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.position
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.position
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.position
     *
     * @param position the value for PLAYER_PERFORMANCE_STAT_PER_GAME.position
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.G
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.G
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Integer getG() {
        return G;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.G
     *
     * @param G the value for PLAYER_PERFORMANCE_STAT_PER_GAME.G
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setG(Integer G) {
        this.G = G;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.GS
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.GS
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Integer getGS() {
        return GS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.GS
     *
     * @param GS the value for PLAYER_PERFORMANCE_STAT_PER_GAME.GS
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setGS(Integer GS) {
        this.GS = GS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.MP
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.MP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getMP() {
        return MP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.MP
     *
     * @param MP the value for PLAYER_PERFORMANCE_STAT_PER_GAME.MP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setMP(Double MP) {
        this.MP = MP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FG
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.FG
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getFG() {
        return FG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FG
     *
     * @param FG the value for PLAYER_PERFORMANCE_STAT_PER_GAME.FG
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setFG(Double FG) {
        this.FG = FG;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FGA
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.FGA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getFGA() {
        return FGA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FGA
     *
     * @param FGA the value for PLAYER_PERFORMANCE_STAT_PER_GAME.FGA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setFGA(Double FGA) {
        this.FGA = FGA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FGP
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.FGP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getFGP() {
        return FGP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FGP
     *
     * @param FGP the value for PLAYER_PERFORMANCE_STAT_PER_GAME.FGP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setFGP(Double FGP) {
        this.FGP = FGP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.3P
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.3P
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double get_3P() {
        return _3P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.3P
     *
     * @param _3P the value for PLAYER_PERFORMANCE_STAT_PER_GAME.3P
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void set_3P(Double _3P) {
        this._3P = _3P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.3PA
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.3PA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double get_3PA() {
        return _3PA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.3PA
     *
     * @param _3PA the value for PLAYER_PERFORMANCE_STAT_PER_GAME.3PA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void set_3PA(Double _3PA) {
        this._3PA = _3PA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.3PP
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.3PP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double get_3PP() {
        return _3PP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.3PP
     *
     * @param _3PP the value for PLAYER_PERFORMANCE_STAT_PER_GAME.3PP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void set_3PP(Double _3PP) {
        this._3PP = _3PP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.2P
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.2P
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double get_2P() {
        return _2P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.2P
     *
     * @param _2P the value for PLAYER_PERFORMANCE_STAT_PER_GAME.2P
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void set_2P(Double _2P) {
        this._2P = _2P;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.2PA
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.2PA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double get_2PA() {
        return _2PA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.2PA
     *
     * @param _2PA the value for PLAYER_PERFORMANCE_STAT_PER_GAME.2PA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void set_2PA(Double _2PA) {
        this._2PA = _2PA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.2PP
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.2PP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double get_2PP() {
        return _2PP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.2PP
     *
     * @param _2PP the value for PLAYER_PERFORMANCE_STAT_PER_GAME.2PP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void set_2PP(Double _2PP) {
        this._2PP = _2PP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.eFGP
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.eFGP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double geteFGP() {
        return eFGP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.eFGP
     *
     * @param eFGP the value for PLAYER_PERFORMANCE_STAT_PER_GAME.eFGP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void seteFGP(Double eFGP) {
        this.eFGP = eFGP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FT
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.FT
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getFT() {
        return FT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FT
     *
     * @param FT the value for PLAYER_PERFORMANCE_STAT_PER_GAME.FT
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setFT(Double FT) {
        this.FT = FT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FTA
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.FTA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getFTA() {
        return FTA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FTA
     *
     * @param FTA the value for PLAYER_PERFORMANCE_STAT_PER_GAME.FTA
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setFTA(Double FTA) {
        this.FTA = FTA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FTP
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.FTP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getFTP() {
        return FTP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.FTP
     *
     * @param FTP the value for PLAYER_PERFORMANCE_STAT_PER_GAME.FTP
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setFTP(Double FTP) {
        this.FTP = FTP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.ORB
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.ORB
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getORB() {
        return ORB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.ORB
     *
     * @param ORB the value for PLAYER_PERFORMANCE_STAT_PER_GAME.ORB
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setORB(Double ORB) {
        this.ORB = ORB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.DRB
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.DRB
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getDRB() {
        return DRB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.DRB
     *
     * @param DRB the value for PLAYER_PERFORMANCE_STAT_PER_GAME.DRB
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setDRB(Double DRB) {
        this.DRB = DRB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.TRB
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.TRB
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getTRB() {
        return TRB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.TRB
     *
     * @param TRB the value for PLAYER_PERFORMANCE_STAT_PER_GAME.TRB
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setTRB(Double TRB) {
        this.TRB = TRB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.AST
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.AST
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getAST() {
        return AST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.AST
     *
     * @param AST the value for PLAYER_PERFORMANCE_STAT_PER_GAME.AST
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setAST(Double AST) {
        this.AST = AST;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.STL
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.STL
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getSTL() {
        return STL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.STL
     *
     * @param STL the value for PLAYER_PERFORMANCE_STAT_PER_GAME.STL
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setSTL(Double STL) {
        this.STL = STL;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.BLK
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.BLK
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getBLK() {
        return BLK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.BLK
     *
     * @param BLK the value for PLAYER_PERFORMANCE_STAT_PER_GAME.BLK
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setBLK(Double BLK) {
        this.BLK = BLK;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.TOV
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.TOV
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getTOV() {
        return TOV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.TOV
     *
     * @param TOV the value for PLAYER_PERFORMANCE_STAT_PER_GAME.TOV
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setTOV(Double TOV) {
        this.TOV = TOV;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.PF
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.PF
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getPF() {
        return PF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.PF
     *
     * @param PF the value for PLAYER_PERFORMANCE_STAT_PER_GAME.PF
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setPF(Double PF) {
        this.PF = PF;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.PTS
     *
     * @return the value of PLAYER_PERFORMANCE_STAT_PER_GAME.PTS
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public Double getPTS() {
        return PTS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_PERFORMANCE_STAT_PER_GAME.PTS
     *
     * @param PTS the value for PLAYER_PERFORMANCE_STAT_PER_GAME.PTS
     *
     * @mbg.generated Mon Nov 09 15:22:35 PST 2020
     */
    public void setPTS(Double PTS) {
        this.PTS = PTS;
    }

}
