package edu.usc.viterbi.dsci.dsci558project.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PlayerBasicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public PlayerBasicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecordIdIsNull() {
            addCriterion("record_id is null");
            return (Criteria) this;
        }

        public Criteria andRecordIdIsNotNull() {
            addCriterion("record_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecordIdEqualTo(String value) {
            addCriterion("record_id =", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotEqualTo(String value) {
            addCriterion("record_id <>", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThan(String value) {
            addCriterion("record_id >", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdGreaterThanOrEqualTo(String value) {
            addCriterion("record_id >=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThan(String value) {
            addCriterion("record_id <", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLessThanOrEqualTo(String value) {
            addCriterion("record_id <=", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdLike(String value) {
            addCriterion("record_id like", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotLike(String value) {
            addCriterion("record_id not like", value, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdIn(List<String> values) {
            addCriterion("record_id in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotIn(List<String> values) {
            addCriterion("record_id not in", values, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdBetween(String value1, String value2) {
            addCriterion("record_id between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andRecordIdNotBetween(String value1, String value2) {
            addCriterion("record_id not between", value1, value2, "recordId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdIsNull() {
            addCriterion("player_id is null");
            return (Criteria) this;
        }

        public Criteria andPlayerIdIsNotNull() {
            addCriterion("player_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerIdEqualTo(String value) {
            addCriterion("player_id =", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotEqualTo(String value) {
            addCriterion("player_id <>", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdGreaterThan(String value) {
            addCriterion("player_id >", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdGreaterThanOrEqualTo(String value) {
            addCriterion("player_id >=", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdLessThan(String value) {
            addCriterion("player_id <", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdLessThanOrEqualTo(String value) {
            addCriterion("player_id <=", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdLike(String value) {
            addCriterion("player_id like", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotLike(String value) {
            addCriterion("player_id not like", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdIn(List<String> values) {
            addCriterion("player_id in", values, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotIn(List<String> values) {
            addCriterion("player_id not in", values, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdBetween(String value1, String value2) {
            addCriterion("player_id between", value1, value2, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotBetween(String value1, String value2) {
            addCriterion("player_id not between", value1, value2, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlIsNull() {
            addCriterion("player_url is null");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlIsNotNull() {
            addCriterion("player_url is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlEqualTo(String value) {
            addCriterion("player_url =", value, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlNotEqualTo(String value) {
            addCriterion("player_url <>", value, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlGreaterThan(String value) {
            addCriterion("player_url >", value, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlGreaterThanOrEqualTo(String value) {
            addCriterion("player_url >=", value, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlLessThan(String value) {
            addCriterion("player_url <", value, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlLessThanOrEqualTo(String value) {
            addCriterion("player_url <=", value, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlLike(String value) {
            addCriterion("player_url like", value, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlNotLike(String value) {
            addCriterion("player_url not like", value, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlIn(List<String> values) {
            addCriterion("player_url in", values, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlNotIn(List<String> values) {
            addCriterion("player_url not in", values, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlBetween(String value1, String value2) {
            addCriterion("player_url between", value1, value2, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerUrlNotBetween(String value1, String value2) {
            addCriterion("player_url not between", value1, value2, "playerUrl");
            return (Criteria) this;
        }

        public Criteria andPlayerNameIsNull() {
            addCriterion("player_name is null");
            return (Criteria) this;
        }

        public Criteria andPlayerNameIsNotNull() {
            addCriterion("player_name is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerNameEqualTo(String value) {
            addCriterion("player_name =", value, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameNotEqualTo(String value) {
            addCriterion("player_name <>", value, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameGreaterThan(String value) {
            addCriterion("player_name >", value, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameGreaterThanOrEqualTo(String value) {
            addCriterion("player_name >=", value, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameLessThan(String value) {
            addCriterion("player_name <", value, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameLessThanOrEqualTo(String value) {
            addCriterion("player_name <=", value, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameLike(String value) {
            addCriterion("player_name like", value, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameNotLike(String value) {
            addCriterion("player_name not like", value, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameIn(List<String> values) {
            addCriterion("player_name in", values, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameNotIn(List<String> values) {
            addCriterion("player_name not in", values, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameBetween(String value1, String value2) {
            addCriterion("player_name between", value1, value2, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerNameNotBetween(String value1, String value2) {
            addCriterion("player_name not between", value1, value2, "playerName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameIsNull() {
            addCriterion("player_full_name is null");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameIsNotNull() {
            addCriterion("player_full_name is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameEqualTo(String value) {
            addCriterion("player_full_name =", value, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameNotEqualTo(String value) {
            addCriterion("player_full_name <>", value, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameGreaterThan(String value) {
            addCriterion("player_full_name >", value, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameGreaterThanOrEqualTo(String value) {
            addCriterion("player_full_name >=", value, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameLessThan(String value) {
            addCriterion("player_full_name <", value, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameLessThanOrEqualTo(String value) {
            addCriterion("player_full_name <=", value, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameLike(String value) {
            addCriterion("player_full_name like", value, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameNotLike(String value) {
            addCriterion("player_full_name not like", value, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameIn(List<String> values) {
            addCriterion("player_full_name in", values, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameNotIn(List<String> values) {
            addCriterion("player_full_name not in", values, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameBetween(String value1, String value2) {
            addCriterion("player_full_name between", value1, value2, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andPlayerFullNameNotBetween(String value1, String value2) {
            addCriterion("player_full_name not between", value1, value2, "playerFullName");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthIsNull() {
            addCriterion("date_of_birth is null");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthIsNotNull() {
            addCriterion("date_of_birth is not null");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthEqualTo(Date value) {
            addCriterion("date_of_birth =", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthNotEqualTo(Date value) {
            addCriterion("date_of_birth <>", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthGreaterThan(Date value) {
            addCriterion("date_of_birth >", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthGreaterThanOrEqualTo(Date value) {
            addCriterion("date_of_birth >=", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthLessThan(Date value) {
            addCriterion("date_of_birth <", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthLessThanOrEqualTo(Date value) {
            addCriterion("date_of_birth <=", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthLike(Date value) {
            addCriterion("date_of_birth like", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthNotLike(Date value) {
            addCriterion("date_of_birth not like", value, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthIn(List<Date> values) {
            addCriterion("date_of_birth in", values, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthNotIn(List<Date> values) {
            addCriterion("date_of_birth not in", values, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthBetween(Date value1, Date value2) {
            addCriterion("date_of_birth between", value1, value2, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andDateOfBirthNotBetween(Date value1, Date value2) {
            addCriterion("date_of_birth not between", value1, value2, "dateOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthIsNull() {
            addCriterion("place_of_birth is null");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthIsNotNull() {
            addCriterion("place_of_birth is not null");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthEqualTo(String value) {
            addCriterion("place_of_birth =", value, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthNotEqualTo(String value) {
            addCriterion("place_of_birth <>", value, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthGreaterThan(String value) {
            addCriterion("place_of_birth >", value, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthGreaterThanOrEqualTo(String value) {
            addCriterion("place_of_birth >=", value, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthLessThan(String value) {
            addCriterion("place_of_birth <", value, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthLessThanOrEqualTo(String value) {
            addCriterion("place_of_birth <=", value, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthLike(String value) {
            addCriterion("place_of_birth like", value, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthNotLike(String value) {
            addCriterion("place_of_birth not like", value, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthIn(List<String> values) {
            addCriterion("place_of_birth in", values, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthNotIn(List<String> values) {
            addCriterion("place_of_birth not in", values, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthBetween(String value1, String value2) {
            addCriterion("place_of_birth between", value1, value2, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andPlaceOfBirthNotBetween(String value1, String value2) {
            addCriterion("place_of_birth not between", value1, value2, "placeOfBirth");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(Double value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(Double value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(Double value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(Double value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(Double value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(Double value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<Double> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<Double> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(Double value1, Double value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(Double value1, Double value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Double value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Double value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Double value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Double value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Double value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Double value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Double> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Double> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Double value1, Double value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Double value1, Double value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andCollegeIsNull() {
            addCriterion("college is null");
            return (Criteria) this;
        }

        public Criteria andCollegeIsNotNull() {
            addCriterion("college is not null");
            return (Criteria) this;
        }

        public Criteria andCollegeEqualTo(String value) {
            addCriterion("college =", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotEqualTo(String value) {
            addCriterion("college <>", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeGreaterThan(String value) {
            addCriterion("college >", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeGreaterThanOrEqualTo(String value) {
            addCriterion("college >=", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLessThan(String value) {
            addCriterion("college <", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLessThanOrEqualTo(String value) {
            addCriterion("college <=", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeLike(String value) {
            addCriterion("college like", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotLike(String value) {
            addCriterion("college not like", value, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeIn(List<String> values) {
            addCriterion("college in", values, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotIn(List<String> values) {
            addCriterion("college not in", values, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeBetween(String value1, String value2) {
            addCriterion("college between", value1, value2, "college");
            return (Criteria) this;
        }

        public Criteria andCollegeNotBetween(String value1, String value2) {
            addCriterion("college not between", value1, value2, "college");
            return (Criteria) this;
        }

        public Criteria andHighSchoolIsNull() {
            addCriterion("high_school is null");
            return (Criteria) this;
        }

        public Criteria andHighSchoolIsNotNull() {
            addCriterion("high_school is not null");
            return (Criteria) this;
        }

        public Criteria andHighSchoolEqualTo(String value) {
            addCriterion("high_school =", value, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolNotEqualTo(String value) {
            addCriterion("high_school <>", value, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolGreaterThan(String value) {
            addCriterion("high_school >", value, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("high_school >=", value, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolLessThan(String value) {
            addCriterion("high_school <", value, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolLessThanOrEqualTo(String value) {
            addCriterion("high_school <=", value, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolLike(String value) {
            addCriterion("high_school like", value, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolNotLike(String value) {
            addCriterion("high_school not like", value, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolIn(List<String> values) {
            addCriterion("high_school in", values, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolNotIn(List<String> values) {
            addCriterion("high_school not in", values, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolBetween(String value1, String value2) {
            addCriterion("high_school between", value1, value2, "highSchool");
            return (Criteria) this;
        }

        public Criteria andHighSchoolNotBetween(String value1, String value2) {
            addCriterion("high_school not between", value1, value2, "highSchool");
            return (Criteria) this;
        }

        public Criteria andDominantHandIsNull() {
            addCriterion("dominant_hand is null");
            return (Criteria) this;
        }

        public Criteria andDominantHandIsNotNull() {
            addCriterion("dominant_hand is not null");
            return (Criteria) this;
        }

        public Criteria andDominantHandEqualTo(String value) {
            addCriterion("dominant_hand =", value, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandNotEqualTo(String value) {
            addCriterion("dominant_hand <>", value, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandGreaterThan(String value) {
            addCriterion("dominant_hand >", value, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandGreaterThanOrEqualTo(String value) {
            addCriterion("dominant_hand >=", value, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandLessThan(String value) {
            addCriterion("dominant_hand <", value, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandLessThanOrEqualTo(String value) {
            addCriterion("dominant_hand <=", value, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandLike(String value) {
            addCriterion("dominant_hand like", value, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandNotLike(String value) {
            addCriterion("dominant_hand not like", value, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandIn(List<String> values) {
            addCriterion("dominant_hand in", values, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandNotIn(List<String> values) {
            addCriterion("dominant_hand not in", values, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandBetween(String value1, String value2) {
            addCriterion("dominant_hand between", value1, value2, "dominantHand");
            return (Criteria) this;
        }

        public Criteria andDominantHandNotBetween(String value1, String value2) {
            addCriterion("dominant_hand not between", value1, value2, "dominantHand");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 09 10:38:24 PST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PLAYER_BASIC
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}