package edu.usc.viterbi.dsci.dsci558project.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class PlayerBasic {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.record_id
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.player_id
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.player_url
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String playerUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.player_name
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String playerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.player_full_name
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String playerFullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.date_of_birth
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.place_of_birth
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String placeOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.height
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private Double height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.weight
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private Double weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.college
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String college;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.high_school
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String highSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.dominant_hand
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String dominantHand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.record_id
     *
     * @return the value of PLAYER_BASIC.record_id
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.record_id
     *
     * @param recordId the value for PLAYER_BASIC.record_id
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.player_id
     *
     * @return the value of PLAYER_BASIC.player_id
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public String getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.player_id
     *
     * @param playerId the value for PLAYER_BASIC.player_id
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setPlayerId(String playerId) {
        this.playerId = playerId == null ? null : playerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.player_url
     *
     * @return the value of PLAYER_BASIC.player_url
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public String getPlayerUrl() {
        return playerUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.player_url
     *
     * @param playerUrl the value for PLAYER_BASIC.player_url
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setPlayerUrl(String playerUrl) {
        this.playerUrl = playerUrl == null ? null : playerUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.player_name
     *
     * @return the value of PLAYER_BASIC.player_name
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public String getPlayerName() {
        return playerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.player_name
     *
     * @param playerName the value for PLAYER_BASIC.player_name
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setPlayerName(String playerName) {
        this.playerName = playerName == null ? null : playerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.player_full_name
     *
     * @return the value of PLAYER_BASIC.player_full_name
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public String getPlayerFullName() {
        return playerFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.player_full_name
     *
     * @param playerFullName the value for PLAYER_BASIC.player_full_name
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setPlayerFullName(String playerFullName) {
        this.playerFullName = playerFullName == null ? null : playerFullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.date_of_birth
     *
     * @return the value of PLAYER_BASIC.date_of_birth
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.date_of_birth
     *
     * @param dateOfBirth the value for PLAYER_BASIC.date_of_birth
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.place_of_birth
     *
     * @return the value of PLAYER_BASIC.place_of_birth
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.place_of_birth
     *
     * @param placeOfBirth the value for PLAYER_BASIC.place_of_birth
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setPlaceOfBirth(String placeOfBirth) {
        this.placeOfBirth = placeOfBirth == null ? null : placeOfBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.height
     *
     * @return the value of PLAYER_BASIC.height
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public Double getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.height
     *
     * @param height the value for PLAYER_BASIC.height
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setHeight(Double height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.weight
     *
     * @return the value of PLAYER_BASIC.weight
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.weight
     *
     * @param weight the value for PLAYER_BASIC.weight
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.college
     *
     * @return the value of PLAYER_BASIC.college
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public String getCollege() {
        return college;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.college
     *
     * @param college the value for PLAYER_BASIC.college
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setCollege(String college) {
        this.college = college == null ? null : college.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.high_school
     *
     * @return the value of PLAYER_BASIC.high_school
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public String getHighSchool() {
        return highSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.high_school
     *
     * @param highSchool the value for PLAYER_BASIC.high_school
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setHighSchool(String highSchool) {
        this.highSchool = highSchool == null ? null : highSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLAYER_BASIC.dominant_hand
     *
     * @return the value of PLAYER_BASIC.dominant_hand
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public String getDominantHand() {
        return dominantHand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLAYER_BASIC.dominant_hand
     *
     * @param dominantHand the value for PLAYER_BASIC.dominant_hand
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    public void setDominantHand(String dominantHand) {
        this.dominantHand = dominantHand == null ? null : dominantHand.trim();
    }

}
