package edu.usc.viterbi.dsci.dsci558project.domain;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class PlayerBasicCompact {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.record_id
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.player_id
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String playerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.player_name
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String playerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.player_full_name
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String playerFullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.date_of_birth
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date dateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLAYER_BASIC.place_of_birth
     *
     * @mbg.generated Mon Nov 09 10:38:24 PST 2020
     */
    private String placeOfBirth;

    public String getRecordId() {
        return recordId;
    }

    public void setRecordId(String recordId) {
        this.recordId = recordId;
    }

    public String getPlayerId() {
        return playerId;
    }

    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }

    public String getPlayerName() {
        return playerName;
    }

    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }

    public String getPlayerFullName() {
        return playerFullName;
    }

    public void setPlayerFullName(String playerFullName) {
        this.playerFullName = playerFullName;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getPlaceOfBirth() {
        return placeOfBirth;
    }

    public void setPlaceOfBirth(String placeOfBirth) {
        this.placeOfBirth = placeOfBirth;
    }

}
